services:
  db:
    image: postgres:16
    container_name: pg-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  wildfly:
    build: .
    image: quay.io/wildfly/wildfly:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/
    depends_on:
      db:
        condition: service_started

volumes:
  pgdata: